# Site settings
title: Jason Huang
email: hjx500@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  JIEXIN HUANG resume CV
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jasonhuang500
github_username: jiexinhuang 

# Build settings
markdown: kramdown
